### GET /messages
GET http://localhost:3000/messages

### POST /messages
POST http://localhost:3000/messages
Content-Type: application/json

{
  "message": "Hello estif's api"
}

### GET /messages/0
GET http://localhost:3000/messages/0

### PATCH /messages/0
PATCH http://localhost:3000/messages/0
Content-Type: application/json

{
  "message": "Updated message!"
}

### DELETE /messages/0
DELETE http://localhost:3000/messages/0